# -*- mode: ruby -*-
# vi: set ft=ruby :
 
Vagrant.configure("2") do |config|
 
  #ansible-redis
  config.vm.define "ansible-redis" do |cfg|
      cfg.vm.box = "centos/7"
      cfg.vm.provider "virtualbox" do |vb|
          vb.name = "ansible-redis"
      end
      cfg.vm.host_name = "ansible-redis"
      cfg.vm.network "public_network", ip: "192.168.1.1"
      cfg.vm.network "forwarded_port", guest: 22, host: 60001, auto_correct: true, id: "ssh"
      cfg.vm.network "forwarded_port", guest: 6379, host: 60081, auto_correct: true
      cfg.vm.synced_folder "../shared_data", "/shared_data", disabled: true

      cfg.vm.provision "shell", path: "./shell/enable_ssh_password_auth.sh"
  end

  #ansible-mongodb
  config.vm.define "ansible-mongodb" do |cfg|
      cfg.vm.box = "centos/7"
      cfg.vm.provider "virtualbox" do |vb|
          vb.name = "ansible-mongodb"
      end
      cfg.vm.host_name = "ansible-mongodb"
      cfg.vm.network "public_network", ip: "192.168.1.3"
      cfg.vm.network "forwarded_port", guest: 22, host: 60003, auto_correct: true, id: "ssh"
      cfg.vm.network "forwarded_port", guest: 27017, host: 60083, auto_correct: true
      cfg.vm.synced_folder "../shared_data", "/shared_data", disabled: true

      cfg.vm.provision "shell", path: "./shell/enable_ssh_password_auth.sh"
  end

  #ansible-server
  config.vm.define "ansible-server" do |cfg|
      cfg.vm.box = "centos/7"
      cfg.vm.provider "virtualbox" do |vb|
          vb.name="ansible-server"
      end
      cfg.vm.host_name = "ansible-server"
      cfg.vm.network "public_network", ip: "192.168.1.10"
      cfg.vm.network "forwarded_port", guest: 22, host: 60010, auto_correct: true, id: "ssh"
      cfg.vm.synced_folder "../shared_data", "/shared_data", disabled: true
      cfg.vm.provision "shell", inline: "yum install epel-release -y"
      cfg.vm.provision "shell", inline: "yum install ansible -y"

      #ansible-node host 설정
      cfg.vm.provision "file", source: "../ansible/setup-ansible-env.yml", destination: "setup-ansible-env.yml"
      cfg.vm.provision "shell", inline: "ansible-playbook setup-ansible-env.yml"
      #ssh setting
      cfg.vm.provision "file", source: "../ansible/auto_ssh_connect.yml", destination: "auto_ssh_connect.yml"
      cfg.vm.provision "shell", inline: "ansible-playbook auto_ssh_connect.yml", privileged: false
      #ansible-redis 서버에 redis 설치
      cfg.vm.provision "file", source: "../ansible/install_redis.yml", destination: "install_redis.yml"
      cfg.vm.provision "shell", inline: "ansible-playbook install_redis.yml"
  end
end